# Generated by Django 6.1.1 on 2026-09-29 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Sqoop', 'Sqoop Import'), ('MapReduce', 'MapReduce Analysis')], max_length=20)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', 'Đang chạy'), ('Completed', 'Hoàn thành'), ('Failed', 'Thất bại')], default='Running', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
