# Generated by Django 6.1.1 on 2026-09-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='job_type',
            field=models.CharField(choices=[('Sqoop', 'Sqoop Import'), ('MapReduce', 'MapReduce Analysis'), ('Hive', 'Hive Query'), ('Pig', 'Pig Script')], max_length=20),
        ),
    ]
